config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, only: [:index, :show, :create, :update, :destroy] do
    resources :messages, only: [:new, :create]
  end
  resources :rooms, only: [:index, :create, :show] do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  room_id    :integer
#  user_id    :integer
#
# Indexes
#
#  index_comments_on_room_id  (room_id)
#  index_comments_on_user_id  (user_id)
#

class Comment < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :body, presence: true

  after_create_commit { CommentBroadcastJob.perform_now self }
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Room < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find_by_id(session[:user_id])
      session[:user_id] = nil unless @current_user
    end
    return @current_user
  end

  def login_required
    return if current_user.present?
    flash[:alert] = 'ユーザーを選択してください'
    redirect_to login_path and return
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @comment = @room.comments.new(comment_params.merge(user: current_user))
    @comment.save
  end

  private def comment_params
    params[:comment].permit(:body)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
  end

  def create
    user = User.find(params[:user_id])
    UserChannel.broadcast_to user, message: render_message(current_user, params[:title], params[:body])
    redirect_to new_user_message_path(user), notice: 'メッセージを送信しました。'
  end

  private def render_message(user, title, body)
    ApplicationController.renderer.render(partial: 'messages/message', locals: { user: user, title: title, body: body })
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to @room
    else
      reder action: :index
    end
  end

  def show
    @room = Room.find(params[:id])
    @comment = @room.comments.build
    @comments = @room.comments.includes(:user).order(created_at: :desc)
  end

  private def room_params
    params[:room].permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      reder action: :index
    end
  end

  def update
    @user = User.find(params[:id])
    session[:user_id] = @user.id
    redirect_to @user
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_path, notive: 'ログアウトしました'
  end

  private def user_params
    params[:user].permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.slim
li
  p= link_to comment.user.name, user_path(comment.user)
  = simple_format comment.body

app/views/comments/_error_field.html.slim
- if comment.errors.present?
  ul
    - comment.errors.full_messages.each do |ms|
      li= ms

app/views/comments/create.js.erb
<% if @comment.valid? %>
  $('#comment_body').val('');
<% else %>
  $('.js-comment-error').html("<%= j(render 'error_field', comment: @comment) %>");
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title ActionCalbeWithTurbolinks
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if current_user.present?
      h1#js-login= "Hi! #{current_user.name} さん"
      = link_to 'ログアウト', user_path(current_user), method: :delete

      ul#js-message-list

    = yield

app/views/messages/_message.html.slim
li
  b= link_to "#{user.name} さんからメッセージ", user_path(user)
  br
  = title
  br
  = simple_format body

app/views/messages/new.html.slim
h2= "#{@user.name} へメッセージを送る"

= form_tag user_messages_path(@user), method: :post do
  = text_field_tag :title
  br
  = text_area_tag :body
  br
  = submit_tag

app/views/rooms/index.html.slim
h2 ルーム一覧

ul
  - @rooms.each do |room|
    li= link_to room.name, room_path(room)

- if @room.errors.present?
  ul
    - @room.errors.full_messages.each do |ms|
      li= ms
= form_for @room do |f|
  = f.text_field :name
  = f.submit

app/views/rooms/show.html.slim
h2#js-room(data-room-id=@room.id )= @room.name

.js-comment-error
  = render 'comments/error_field', comment: @comment

= form_for [@room, @comment], data: { remote: true } do |f|
  = f.text_area :body
  = f.submit

ul.js-commnent-list
  = render @comments

app/views/users/index.html.slim
h2 ユーザー一覧

h2 ログイン
ul
  - @users.each do |user|
    li= link_to user.name, user_path(user), method: :patch

- if @user.errors.present?
  ul
    - @user.errors.full_messages.each do |ms|
      li= ms
= form_for @user do |f|
  = f.text_field :name
  = f.submit

app/views/users/show.html.slim
h2= @user.name

- if @user != current_user
  = linl_to 'メッセージを送る', new_user_message_path(@user)

= link_to 'チャットルームを探す', rooms_path